apiVersion: v1
kind: Service
metadata:
  name: lam
  labels:
    managed-by: iac
spec:
  selector:
    app: lam
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
