apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    managed-by: iac
spec:
  type: ClusterIP
  ports:
    - port: 389
      targetPort: 389
      name: ldap
    - port: 636
      targetPort: 636
      name: ldaps
  selector:
    app: openldap
