kubectl delete all --all -n default
kubectl delete pvc --all -n default
kubectl delete configmap --all -n default
kubectl delete secret --all -n default
kubectl delete ingress --all -n default
kubectl delete serviceaccount --all -n default
kubectl delete cronjobs --all -n default
kubectl delete jobs --all -n default
kubectl delete role --all -n default
kubectl delete rolebinding --all -n default
kubectl delete networkpolicy --all -n default
kubectl delete horizontalpodautoscaler --all -n default
