apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-ml
  template:
    metadata:
      labels:
        app: immich-ml
    spec:
      containers:
        - name: immich-ml
          image: ghcr.io/immich-app/immich-machine-learning:release
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: IMMICH_PORT
              value: "2283"
          volumeMounts:
            - name: model-cache
              mountPath: /cache
      volumes:
        - name: model-cache
          hostPath:
            # path: /home/dani/storage/immich-cache
            path: /Users/danielramos/Documents/storage/ssd/immich-cache
            type: DirectoryOrCreate
