apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    managed-by: iac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
          env:
            - name: POSTGRES_PASSWORD
              value: "changeme"
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
            - name: DATABASE_USERS
              value: "immich,authentik"
            - name: USER_PASSWORD_IMMICH
              value: "c0aec791-f4a4-4873-aed7-1e343daee907"
            - name: USER_PASSWORD_AUTHENTIK
              value: "d9a14e19-2495-4598-820e-21a50c0f5f10"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: db-data
          hostPath:
            # path: /home/dani/storage/postgres
            path: /Users/danielramos/Documents/storage/ssd/postgres
            type: DirectoryOrCreate
        - name: init-script
          configMap:
            name: postgres-init-script
