image:
  tag: v1.135.3

env:
  DB_HOSTNAME: "postgres-postgresql.postgres.svc.cluster.local"
  DB_PORT: "5432"
  DB_USERNAME: "immich"
  DB_PASSWORD: "c0aec791-f4a4-4873-aed7-1e343daee907"
  DB_DATABASE_NAME: "immich"

  REDIS_HOSTNAME: "valkey-primary.valkey.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "password"

immich:
  persistence:
    library:
      existingClaim: immich-library-pvc
  configuration:
    storageTemplate:
      enabled: true
      template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"

server:
  ingress:
    main:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: photos.danielramos.me
          paths:
            - path: "/"
      tls:
        - hosts:
            - photos.danielramos.me
          secretName: immich-tls
