apiVersion: v1
kind: Service
metadata:
  name: authentik
spec:
  type: NodePort
  selector:
    app: authentik-server
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 30900
    - name: https
      port: 9443
      targetPort: 9443
      nodePort: 30943
