apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentik-server
  template:
    metadata:
      labels:
        app: authentik-server
    spec:
      containers:
        - name: server
          image: ghcr.io/goauthentik/server:2025.6.3
          args: ["server"]
          ports:
            - containerPort: 9000
            - containerPort: 9443
          env:
            - name: AUTHENTIK_SECRET_KEY
              value: "84762e73-f18c-4c57-8928-0710a8c78921"
            - name: AUTHENTIK_REDIS__HOST
              value: "cache"
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: "postgres"
            - name: AUTHENTIK_POSTGRESQL__USER
              value: "authentik"
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: "authentik"
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              value: "d9a14e19-2495-4598-820e-21a50c0f5f10"
          volumeMounts:
            - name: media
              mountPath: /media
            - name: custom-templates
              mountPath: /templates
      volumes:
        - name: media
          hostPath:
            path: /srv/authentik/media
        - name: custom-templates
          hostPath:
            path: /srv/authentik/custom-templates
