apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentik-worker
  template:
    metadata:
      labels:
        app: authentik-worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/goauthentik/server:2025.6.3
          args: ["worker"]
          securityContext:
            runAsUser: 0
          env:
            - name: AUTHENTIK_SECRET_KEY
              value: "changeme-this-should-be-random"
            - name: AUTHENTIK_REDIS__HOST
              value: "cache"
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: "postgres"
            - name: AUTHENTIK_POSTGRESQL__USER
              value: "authentik"
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: "authentik"
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              value: "d9a14e19-2495-4598-820e-21a50c0f5f10"
          volumeMounts:
            - name: media
              mountPath: /media
            - name: certs
              mountPath: /certs
            - name: custom-templates
              mountPath: /templates
      volumes:
        - name: media
          hostPath:
            path: /srv/authentik/media
        - name: certs
          hostPath:
            path: /srv/authentik/certs
        - name: custom-templates
          hostPath:
            path: /srv/authentik/custom-templates
