apiVersion: v1
kind: Service
metadata:
  name: immich
  labels:
    managed-by: iac
spec:
  selector:
    app: immich
  ports:
    - protocol: TCP
      port: 2283
      targetPort: 2283
      nodePort: 32283
  type: NodePort
