# yaml-language-server: $schema=https://raw.githubusercontent.com/bitnami/charts/refs/tags/valkey/3.0.17/bitnami/valkey/values.schema.json

architecture: standalone

auth:
  password: "password"

primary:
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
  persistence:
    enabled: false
